import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Weapons } from '../Weapons';


@Injectable()
export class WeaponsProvider {

  listWeapons: Weapons[] =
    [
      { name: "UMP-45", side: "both", category: "smg", price: "1,200", magazine: "25", capacity: "100", reward: "600", damages: "35", cadence: "11", recoilcontrol: "76", distanceprecision: "11", armourpenetration: "130", force: "1", stoppower: "100", description: "", releasedate: "", img: "../../assets/imgs/weapons/ump45.png", gif: "<img src='../../assets/imgs/weapons/gif/ump45.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "P90", side: "both", category: "smg", price: "2,350", magazine: "50", capacity: "100", reward: "300", damages: "26", cadence: "14", recoilcontrol: "85", distanceprecision: "11", armourpenetration: "132", force: "1", stoppower: "100", description: "", releasedate: "", img: "../../assets/imgs/weapons/p90.png", gif: "<img src='../../assets/imgs/weapons/gif/p90.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "Glock-18", side: "terrorist", category: "pistol", price: "200", magazine: "20", capacity: "120", reward: "300", damages: "30", cadence: "6", recoilcontrol: "83", distanceprecision: "22", armourpenetration: "94", force: "1", stoppower: "50", description: "", releasedate: "", img: "../../assets/imgs/weapons/glock.png", gif: "<img src='../../assets/imgs/weapons/gif/glock.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "Dual Berettas", side: "both", category: "pistol", price: "400", magazine: "30", capacity: "120", reward: "300", damages: "38", cadence: "8", recoilcontrol: "68", distanceprecision: "18", armourpenetration: "115", force: "1", stoppower: "50", description: "", releasedate: "", img: "../../assets/imgs/weapons/berretta.png", gif: "<img src='../../assets/imgs/weapons/gif/berretta.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "P250", side: "both", category: "pistol", price: "300", magazine: "13", capacity: "26", reward: "300", damages: "38", cadence: "9", recoilcontrol: "70", distanceprecision: "15", armourpenetration: "128", force: "1", stoppower: "50", description: "", releasedate: "", img: "../../assets/imgs/weapons/P250.png", gif: "<img src='../../assets/imgs/weapons/gif/P250.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "CZ75-Auto", side: "both", category: "pistol", price: "500", magazine: "12", capacity: "12", reward: "100", damages: "31", cadence: "10", recoilcontrol: "59", distanceprecision: "12", armourpenetration: "155", force: "1", stoppower: "50", description: "", releasedate: "", img: "../../assets/imgs/weapons/CZ75.png", gif: "<img src='../../assets/imgs/weapons/gif/CZ75.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "Desert Eagle", side: "both", category: "pistol", price: "700", magazine: "7", capacity: "35", reward: "300", damages: "63", cadence: "4", recoilcontrol: "9", distanceprecision: "27", armourpenetration: "186", force: "2", stoppower: "60", description: "", releasedate: "", img: "../../assets/imgs/weapons/deagle.png", gif: "<img src='../../assets/imgs/weapons/gif/deagle.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "Nova", side: "both", category: "heavy", price: "1,200", magazine: "8", capacity: "32", reward: "900", damages: "234", cadence: "1", recoilcontrol: "1", distanceprecision: "3", armourpenetration: "100", force: "0", stoppower: "540", description: "", releasedate: "", img: "../../assets/imgs/weapons/nova.png", gif: "<img src='../../assets/imgs/weapons/gif/nova.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "XM1014", side: "both", category: "heavy", price: "2,000", magazine: "7", capacity: "32", reward: "900", damages: "120", cadence: "2", recoilcontrol: "1", distanceprecision: "3", armourpenetration: "160", force: "1", stoppower: "360", description: "", releasedate: "", img: "../../assets/imgs/weapons/xm1014.png", gif: "<img src='../../assets/imgs/weapons/gif/xm1014.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "Sawed-off", side: "terrorist", category: "heavy", price: "1,200", magazine: "7", capacity: "32", reward: "900", damages: "256", cadence: "1", recoilcontrol: "1", distanceprecision: "2", armourpenetration: "150", force: "1", stoppower: "480", description: "", releasedate: "", img: "../../assets/imgs/weapons/sawedoff.png", gif: "<img src='../../assets/imgs/weapons/gif/sawedoff.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "M249", side: "both", category: "heavy", price: "5,200", magazine: "100", capacity: "200", reward: "300", damages: "32", cadence: "12", recoilcontrol: "72", distanceprecision: "17", armourpenetration: "160", force: "2", stoppower: "60", description: "", releasedate: "", img: "../../assets/imgs/weapons/m249.png", gif: "<img src='../../assets/imgs/weapons/gif/m249.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "Negev", side: "both", category: "heavy", price: "1,700", magazine: "150", capacity: "300", reward: "300", damages: "35", cadence: "13", recoilcontrol: "79", distanceprecision: "13", armourpenetration: "142", force: "2", stoppower: "60", description: "", releasedate: "", img: "../../assets/imgs/weapons/negev.png", gif: "<img src='../../assets/imgs/weapons/gif/negev.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "Mac-10", side: "terrorist", category: "smg", price: "1,050", magazine: "30", capacity: "100", reward: "600", damages: "29", cadence: "13", recoilcontrol: "83", distanceprecision: "12", armourpenetration: "115", force: "1", stoppower: "100", description: "", releasedate: "", img: "../../assets/imgs/weapons/mac10.png", gif: "<img src='../../assets/imgs/weapons/gif/mac10.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "MP7", side: "both", category: "smg", price: "1,500", magazine: "30", capacity: "120", reward: "600", damages: "29", cadence: "12", recoilcontrol: "85", distanceprecision: "15", armourpenetration: "125", force: "1", stoppower: "100", description: "", releasedate: "", img: "../../assets/imgs/weapons/mp7.png", gif: "<img src='../../assets/imgs/weapons/gif/mp7.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "MP9", side: "counter", category: "smg", price: "1,250", magazine: "30", capacity: "120", reward: "600", damages: "26", cadence: "14", recoilcontrol: "81", distanceprecision: "17", armourpenetration: "120", force: "1", stoppower: "100", description: "", releasedate: "", img: "../../assets/imgs/weapons/mp9.png", gif: "<img src='../../assets/imgs/weapons/gif/mp9.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "PP-Bizon", side: "both", category: "smg", price: "1,400", magazine: "64", capacity: "120", reward: "600", damages: "27", cadence: "12", recoilcontrol: "83", distanceprecision: "11", armourpenetration: "115", force: "1", stoppower: "100", description: "", releasedate: "", img: "../../assets/imgs/weapons/ppbizon.png", gif: "<img src='../../assets/imgs/weapons/gif/ppbizon.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "Ak-47", side: "terrorist", category: "rifle", price: "2,700", magazine: "30", capacity: "90", reward: "300", damages: "36", cadence: "10", recoilcontrol: "68", distanceprecision: "24", armourpenetration: "155", force: "2", stoppower: "60", description: "", releasedate: "", img: "../../assets/imgs/weapons/ak47.png", gif: "<img src='../../assets/imgs/weapons/gif/ak47.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "SSG 08", side: "both", category: "rifle", price: "1,700", magazine: "10", capacity: "90", reward: "300", damages: "88", cadence: "0", recoilcontrol: "44", distanceprecision: "52", armourpenetration: "170", force: "2", stoppower: "65", description: "", releasedate: "", img: "../../assets/imgs/weapons/ssg08.png", gif: "<img src='../../assets/imgs/weapons/gif/ssg08.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "SG 553", side: "terrorist", category: "rifle", price: "2,750", magazine: "30", capacity: "90", reward: "300", damages: "30", cadence: "11", recoilcontrol: "68", distanceprecision: "39", armourpenetration: "200", force: "2", stoppower: "60", description: "", releasedate: "", img: "../../assets/imgs/weapons/sg553.png", gif: "<img src='../../assets/imgs/weapons/gif/sg553.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "AWP", side: "both", category: "rifle", price: "4,750", magazine: "10", capacity: "30", reward: "100", damages: "115", cadence: "0", recoilcontrol: "1", distanceprecision: "76", armourpenetration: "195", force: "2", stoppower: "65", description: "", releasedate: "", img: "../../assets/imgs/weapons/awp.png", gif: "<img src='../../assets/imgs/weapons/gif/awp.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "G3SG1", side: "terrorist", category: "rifle", price: "5,000", magazine: "20", capacity: "90", reward: "300", damages: "80", cadence: "4", recoilcontrol: "63", distanceprecision: "73", armourpenetration: "165", force: "2", stoppower: "50", description: "", releasedate: "", img: "../../assets/imgs/weapons/g3sg1.png", gif: "<img src='../../assets/imgs/weapons/gif/g3sg1.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "USP-S", side: "counter", category: "pistol", price: "200", magazine: "12", capacity: "24", reward: "300", damages: "35", cadence: "5", recoilcontrol: "70", distanceprecision: "22", armourpenetration: "101", force: "1", stoppower: "50", description: "", releasedate: "", img: "../../assets/imgs/weapons/usp.png", gif: "<img src='../../assets/imgs/weapons/gif/usp.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "AUG", side: "counter", category: "rifle", price: "3,150", magazine: "30", capacity: "90", reward: "300", damages: "28", cadence: "11", recoilcontrol: "76", distanceprecision: "38", armourpenetration: "180", force: "2", stoppower: "60", description: "", releasedate: "", img: "../../assets/imgs/weapons/aug.png", gif: "<img src='../../assets/imgs/weapons/gif/aug.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "SCAR-20", side: "counter", category: "rifle", price: "5,000", magazine: "20", capacity: "90", reward: "300", damages: "80", cadence: "4", recoilcontrol: "62", distanceprecision: "73", armourpenetration: "165", force: "2", stoppower: "65", description: "", releasedate: "", img: "../../assets/imgs/weapons/scar20.png", gif: "<img src='../../assets/imgs/weapons/gif/scar20.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "Famas", side: "counter", category: "rifle", price: "2,250", magazine: "25", capacity: "90", reward: "300", damages: "30", cadence: "11", recoilcontrol: "80", distanceprecision: "16", armourpenetration: "140", force: "2", stoppower: "60", description: "", releasedate: "", img: "../../assets/imgs/weapons/famas.png", gif: "<img src='../../assets/imgs/weapons/gif/famas.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "MAG-7", side: "counter", category: "heavy", price: "1,800", magazine: "2", capacity: "32", reward: "900", damages: "240", cadence: "1", recoilcontrol: "1", distanceprecision: "3", armourpenetration: "150", force: "1", stoppower: "480", description: "", releasedate: "", img: "../../assets/imgs/weapons/mag7.png", gif: "<img src='../../assets/imgs/weapons/gif/mag7.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "MP9", side: "counter", category: "smg", price: "1,250", magazine: "30", capacity: "120", reward: "400", damages: "26", cadence: "14", recoilcontrol: "81", distanceprecision: "17", armourpenetration: "120", force: "1", stoppower: "100", description: "", releasedate: "", img: "../../assets/imgs/weapons/mp9.png", gif: "<img src='../../assets/imgs/weapons/gif/mp9.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "Galil", side: "terrorist", category: "rifle", price: "2,000", magazine: "35", capacity: "90", reward: "300", damages: "30", cadence: "11", recoilcontrol: "79", distanceprecision: "18", armourpenetration: "155", force: "2", stoppower: "60", description: "", releasedate: "", img: "../../assets/imgs/weapons/galil.png", gif: "<img src='../../assets/imgs/weapons/gif/galil.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "Tec-9", side: "terrorist", category: "pistol", price: "500", magazine: "18", capacity: "90", reward: "300", damages: "33", cadence: "8", recoilcontrol: "74", distanceprecision: "24", armourpenetration: "181", force: "1", stoppower: "50", description: "", releasedate: "", img: "../../assets/imgs/weapons/tec9.png", gif: "<img src='../../assets/imgs/weapons/gif/tec9.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "Revolver R8", side: "both", category: "pistol", price: "600", magazine: "8", capacity: "8", reward: "300", damages: "86", cadence: "2", recoilcontrol: "81", distanceprecision: "67", armourpenetration: "186", force: "2", stoppower: "60", description: "", releasedate: "", img: "../../assets/imgs/weapons/revolver.png", gif: "<img src='../../assets/imgs/weapons/gif/revolver.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "MP5SD", side: "both", category: "smg", price: "1,500", magazine: "30", capacity: "120", reward: "600", damages: "27", cadence: "12", recoilcontrol: "85", distanceprecision: "15", armourpenetration: "125", force: "1", stoppower: "100", description: "", releasedate: "", img: "../../assets/imgs/weapons/mp5sd.png", gif: "<img src='../../assets/imgs/weapons/gif/mp5sd.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "P2000", side: "counter", category: "pistol", price: "200", magazine: "13", capacity: "52", reward: "300", damages: "35", cadence: "5", recoilcontrol: "73", distanceprecision: "24", armourpenetration: "101", force: "1", stoppower: "50", description: "", releasedate: "", img: "../../assets/imgs/weapons/p2000.png", gif: "<img src='../../assets/imgs/weapons/gif/p2000.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "Five-SeveN", side: "counter", category: "pistol", price: "500", magazine: "20", capacity: "100", reward: "300", damages: "32", cadence: "6", recoilcontrol: "70", distanceprecision: "15", armourpenetration: "182", force: "1", stoppower: "50", description: "", releasedate: "", img: "../../assets/imgs/weapons/fiveseven.png", gif: "<img src='../../assets/imgs/weapons/gif/fiveseven.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "M4A1-s", side: "counter", category: "rifle", price: "3,100", magazine: "20", capacity: "60", reward: "300", damages: "33", cadence: "10", recoilcontrol: "71", distanceprecision: "30", armourpenetration: "140", force: "2", stoppower: "60", description: "", releasedate: "", img: "../../assets/imgs/weapons/m4a1s.png", gif: "<img src='../../assets/imgs/weapons/gif/m4a1s.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "M4A4", side: "counter", category: "rifle", price: "3,100", magazine: "30", capacity: "90", reward: "300", damages: "33", cadence: "11", recoilcontrol: "77", distanceprecision: "30", armourpenetration: "140", force: "2", stoppower: "60", description: "", releasedate: "", img: "../../assets/imgs/weapons/m4a4.png", gif: "<img src='../../assets/imgs/weapons/gif/m4a4.gif'>", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "HE", side: "both", category: "grenade", price: "300", magazine: "1", capacity: "1", reward: "300", damages: "57", cadence: "None", recoilcontrol: "None", distanceprecision: "None", armourpenetration: "2", force: "None", stoppower: "None", description: "", releasedate: "", img: "../../assets/imgs/weapons/he.png", gif: "", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "Incendiary", side: "counter", category: "grenade", price: "600", magazine: "1", capacity: "1", reward: "300", damages: "8\/hit", cadence: "1", recoilcontrol: "None", distanceprecision: "None", armourpenetration: "100", force: "None", stoppower: "None", description: "", releasedate: "", img: "../../assets/imgs/weapons/incendiary.png", gif: "", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "Molotov", side: "terrorist", category: "grenade", price: "400", magazine: "1", capacity: "1", reward: "300", damages: "8\/hit", cadence: "None", recoilcontrol: "None", distanceprecision: "None", armourpenetration: "100", force: "None", stoppower: "None", description: "", releasedate: "", img: "../../assets/imgs/weapons/molotov.png", gif: "", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "Flashbang", side: "both", category: "grenade", price: "200", magazine: "1", capacity: "2", reward: "300", damages: "2", cadence: "None", recoilcontrol: "None", distanceprecision: "None", armourpenetration: "None", force: "None", stoppower: "None", description: "", releasedate: "", img: "../../assets/imgs/weapons/flashbang.png", gif: "", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "Decoy", side: "both", category: "grenade", price: "50", magazine: "1", capacity: "1", reward: "300", damages: "2", cadence: "None", recoilcontrol: "None", distanceprecision: "None", armourpenetration: "None", force: "None", stoppower: "None", description: "", releasedate: "", img: "../../assets/imgs/weapons/decoy.png", gif: "", properties: "", autre1: "", autre2: "", autre3: "" },
      { name: "Smoke", side: "both", category: "grenade", price: "300", magazine: "1", capacity: "1", reward: "300", damages: "2", cadence: "None", recoilcontrol: "None", distanceprecision: "None", armourpenetration: "None", force: "None", stoppower: "None", description: "", releasedate: "", img: "../../assets/imgs/weapons/smoke.png", gif: "", properties: "", autre1: "", autre2: "", autre3: "" }
    ]
    

  constructor() {
    console.log('Hello CompetitiveMapPoolProvider Provider');
  }

  getListWeapons(): Weapons[] {
    return this.listWeapons;
  }

}
